const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"婚礼公司管理",
                        "menuJump":"列表",
                        "tableName":"hunligongsi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"婚礼公司收藏管理",
                        "menuJump":"列表",
                        "tableName":"hunligongsiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"婚礼公司预约管理",
                        "menuJump":"列表",
                        "tableName":"hunligongsiOrder"
                    }
                ],
                "menu":"婚礼公司管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"结婚案例管理",
                        "menuJump":"列表",
                        "tableName":"jiehunanli"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"结婚案例收藏管理",
                        "menuJump":"列表",
                        "tableName":"jiehunanliCollection"
                    }
                ],
                "menu":"结婚案例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"相亲管理",
                        "menuJump":"列表",
                        "tableName":"xiangqin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"相亲留言管理",
                        "menuJump":"列表",
                        "tableName":"xiangqinLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"相亲收藏管理",
                        "menuJump":"列表",
                        "tableName":"xiangqinCollection"
                    }
                ],
                "menu":"相亲管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"婚礼公司管理",
                        "menuJump":"列表",
                        "tableName":"hunligongsi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"婚礼公司收藏管理",
                        "menuJump":"列表",
                        "tableName":"hunligongsiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"婚礼公司预约管理",
                        "menuJump":"列表",
                        "tableName":"hunligongsiOrder"
                    }
                ],
                "menu":"婚礼公司管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"结婚案例管理",
                        "menuJump":"列表",
                        "tableName":"jiehunanli"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"结婚案例收藏管理",
                        "menuJump":"列表",
                        "tableName":"jiehunanliCollection"
                    }
                ],
                "menu":"结婚案例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"相亲管理",
                        "menuJump":"列表",
                        "tableName":"xiangqin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"相亲留言管理",
                        "menuJump":"列表",
                        "tableName":"xiangqinLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"相亲收藏管理",
                        "menuJump":"列表",
                        "tableName":"xiangqinCollection"
                    }
                ],
                "menu":"相亲管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
